# Generated by Django 4.0.4 on 2022-06-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RED', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qurans_ayats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=32)),
                ('ayats', models.JSONField(default=dict)),
            ],
        ),
    ]
